# Generated by Django 4.2 on 2023-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='title',
            field=models.CharField(max_length=128, verbose_name='First Name'),
        ),
    ]
